### ISSUE TITLE
Upgrade guide from 1.x.x -> 2.x.x

### ISSUE THREAD

**Issue by lewisf** [honeycombio/beeline-ruby#127]
I noticed there was a major version release (2.0.0), but don't notice anything in the `UPGRADING.md`

Is it safe to assume there aren't any backwards incompatible changes that I need to worry about?

**Comment by paulosman** [comment]
Hi, @lewisf thanks for raising this! I've created a PR to add an explanatory note, but the short version is that you don't need to worry about code changes - just instrumentation changes. Fields in your dataset may go missing, be renamed, other fields will be added, etc.
