### ISSUE TITLE
Custom Sampling example doesn't work

### ISSUE THREAD

**Issue by omnibs** [honeycombio/beeline-ruby#137]
The example in [Customizing Sampling Logic](https://docs.honeycomb.io/getting-data-in/ruby/beeline/#customizing-sampling-logic) in the docs always has a sample rate of 1. The `fields['app.response_code']` field is never set.

I did notice that `response.status_code` is a thing in the root span with `beeline-ruby`. But it is a thing only in the root span, and I also noticed the `sample_hook` is executed for every span created in a request, before it ends.

Can we ignore non-root spans in `sample_hook` and use `response.status_code` instead of `app.response_code`?

Edit: I guess https://github.com/honeycombio/beeline-ruby/pull/115 answers my question on `sample_hook` running for every span. So we do send every span ahead of time before the root span is finished. In order to not send incomplete traces, we should only sample the root span, and continue sending all inner spans, which is unfortunate. At least until #115 is done, I guess.

**Comment by ajvondrak** [comment]
Yeah, that example is misleading due to how the sampling hook actually works. [This post](https://www.honeycomb.io/blog/honeybyte-get-a-taste-for-sampling/) explains the usage & pitfalls a lot better. See also the discussion on #83.

**Comment by omnibs** [comment]
Thanks for the links, very informative!

Probably not the best avenue, but I do wanna register for HC folks that the tradeoffs of head-based sampling and the combo of beeline-ruby + Refinery/OpenTelemetry collector are not a match for for my team, unfortunately 😞 

- We don't have such strict memory and response time requirements that tail-based sampling would hurt. I could guess most Rails shops are in the same boat. For performance-critical stuff we use Haskell.
- We are a small team and don't want to provision / manage / upgrade / debug Refinery / OpenTelemetry collector.
- We'd rather have consistent traces (either drop entire trace+children, or keep entire trace+children). I'd be open to be convinced otherwise, but I imagine inconsistent traces (with missing spans) will mislead our team when investigating issues.
- We'll need to sample heavily.

For Haskell we are rolling our own integration and are using tail-based sampling. I haven't turned it on in our highest traffic service yet. Now I'm curious if we'll see an impact in memory usage or response time.

**Comment by MikeGoldsmith** [comment]
Closing this issue as it's not something we're going implement in the beeline directly.

The best solution is to use refinery / OpenTelemetry collector - we understand running extra infrastructure is not ideal for everyone, but tail based sampling is a complex issue and something we feel should not be done at the SDK level.
