### ISSUE TITLE
Support for TestClient

### ISSUE THREAD

**Issue by rhymes** [honeycombio/beeline-ruby#14]
If would be nice if `Honeycomb.init` being a high level interface of client instantiation would support [LibHoney::TestClient](https://www.rubydoc.info/gems/libhoney/Libhoney/TestClient) given that there's no `attr_writer` for `client` nor the client can be passed from the outside as an injected dependency.

It would also be nice if there was in the testing mode not to autoinstall `Faraday::Honeycomb` which seem to conflict with other gems. It ends up in a `SystemError: can't modify middleware stack after making a request` and a warning: `WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.`

Thank you

**Comment by martin308** [comment]
This is completed in `v1.0.0`!

You can pass in your own custom libhoney client as part of the configuration!

```
Honeycomb.configure do |config|
  config.client = Libhoney::TestClient.new
end
```
