### ISSUE TITLE
Heroku build fails when adding gem to Gemfile

### ISSUE THREAD

**Issue by israveri** [honeycombio/beeline-ruby#148]
Hi,

Adding the `honeycomb-beeline` gem in the application breaks the Heroku build with the error below, even though it builds fine locally. I've tried searching for a solution looking for problems with http-parser directly but with no luck. Any ideas of what the problem might be?

Building with:

Heroku-20 stack
Ruby 3.0.1
Rails 6.1.3.2
Bundler 2.2.16

       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       
       current directory:
       /tmp/build_ae088ca3/vendor/bundle/ruby/3.0.0/gems/http-parser-1.2.3/ext
       /tmp/build_ae088ca3/vendor/ruby-3.0.1/bin/ruby
       -I/tmp/build_ae088ca3/vendor/ruby-3.0.1/lib/ruby/3.0.0 -rrubygems
       /tmp/build_ae088ca3/vendor/bundle/ruby/3.0.0/gems/rake-12.3.3/exe/rake
       RUBYARCHDIR\=/tmp/build_ae088ca3/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/http-parser-1.2.3
       RUBYLIBDIR\=/tmp/build_ae088ca3/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/http-parser-1.2.3
       rake aborted!
       ArgumentError: wrong number of arguments (given 2, expected 1)
       /tmp/build_ae088ca3/vendor/bundle/ruby/3.0.0/gems/rake-12.3.3/exe/rake:27:in
       `<main>'
       Tasks: TOP => default => x86_64-linux/libhttp-parser-ext.so =>
       x86_64-linux/http-parser/http_parser.o => x86_64-linux/http-parser
       (See full trace by running task with --trace)
       
       rake failed, exit code 1
       
       Gem files will remain installed in
       /tmp/build_ae088ca3/vendor/bundle/ruby/3.0.0/gems/http-parser-1.2.3 for
       inspection.
       Results logged to
       /tmp/build_ae088ca3/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/http-parser-1.2.3/gem_make.out
       
       An error occurred while installing http-parser (1.2.3), and Bundler cannot
       continue.
       Make sure that `gem install http-parser -v '1.2.3' --source
       'https://rubygems.org/'` succeeds before bundling.
       
       In Gemfile:
         honeycomb-beeline was resolved to 2.4.0, which depends on
           libhoney was resolved to 1.18.0, which depends on
             http was resolved to 4.4.1, which depends on
               http-parser

**Comment by arbales** [comment]
I'm having the same problem with http-parser.

**Comment by JamieDanielson** [comment]
@arbales Do you by chance have an example of a repro you can provide? I deployed a standalone version of [year service from our example-greeting-service repo](https://github.com/honeycombio/example-greeting-service/tree/main/ruby/year-service), and didn't have this error. 

Portion of my Build Log in case it helps with comparison:

```
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/ruby
-----> Ruby app detected
-----> Installing bundler 2.2.21
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.7.5
-----> Installing dependencies using bundler 2.2.21

...
       Using http-parser 1.2.3
       Using http 4.4.1
       Using libhoney 1.18.0
       Using honeycomb-beeline 2.4.2

...

       Bundle complete! 3 Gemfile dependencies, 37 gems now installed.
```

**Comment by arbales** [comment]
I solved this problem by using the HTTP gem from Github which no longer has the old http parser dep.

**Comment by JamieDanielson** [comment]
Ah, thanks for the update @arbales, good to know that worked. We'll take a look to see if there's something we should address with the beeline at this time.

**Comment by arbales** [comment]
This was for a different gem with the same dep (http parser) but you’ll
likely trigger the error on Ruby 3.1.0 when deploying to Heroku.

**Comment by JamieDanielson** [comment]
I didn't get the error when upgrading to Ruby 3.1.0 unfortunately, but it sounds like the issue is specific to the old http-parser which I believe is coming from libhoney's http dependency. We'll take a look there and see what's involved in changing that out.

**Comment by JamieDanielson** [comment]
Reviewing this further... it seems that if this build error comes up when using the ruby beeline, it is resolvable by specifying a newer version of http in your gem file that doesn't rely on http-parser.

If that is the case, that is probably the best solution at this time. We are intentionally slow to deprecate older versions of libraries if we can avoid it, and there is not an easy upgrade for http that does not potentially cut off support for other libraries, as it's already specified for a range of versions in libhoney.

Since I am unable to reproduce the build error I am assuming it's a specific combination of gems that I'm not using... but if the advice of providing a specific http gem is incorrect please let me know.
