### ISSUE TITLE
Address CodeCov gem deprecation and the errors in the nightly.

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/beeline-ruby#168]
The nightlies are failing because of CodeCov's API being upset that our very wide test matrix submits coverage reports for the same commit (main's current) in quick succession.

1. We don't really need coverage tracking reported for the nightly build. We ought to turn off reporting in that workflow.
2. [CodeCov has switched to using an external binary to report coverage instead of language-specific libraries](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/). If we're going to keep CodeCov, we ought to switch to that.

**Comment by JamieDanielson** [comment]
Look to remove CodeCov completely, and later if we decide to add back we can.
