### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by DanielHeath** [honeycombio/beeline-ruby#19]
I've deployed this on a single canary instance in production, and the CPU utilization more than doubled!

I should be able to pull in an rbspy trace soon, but the only thing that's changed is enabling beeline. 

This would essentially double our hosting costs, which makes the financial case for honeycomb harder to make than I'd like.

**Comment by DanielHeath** [comment]
Not sure why this happened previously; I've since tried to reproduce and can't.

**Comment by martin308** [comment]
@DanielHeath thanks for keeping us up to date! Happy to help investigate if you come up with any more information

**Comment by directionless** [comment]
I documented some performance issues in https://github.com/honeycombio/beeline-ruby/issues/57
