### ISSUE TITLE
Documentation: adding context

### ISSUE THREAD

**Issue by DanielHeath** [honeycombio/beeline-ruby#20]
The documentation at https://docs.honeycomb.io/getting-data-in/ruby/beeline/#adding-context-to-events shows how to add context to a sinatra app. 

To add it to a rails app, you need to change:

 * `request.env` instead of `env`
 * `Rack::Honeycomb.add_field` to a method that exists (this missing method is also referenced in the upgrade guide). Actually, if someone could let me know what that method is, that'd be super handy.

**Comment by martin308** [comment]
@DanielHeath this is now much easier in `v1.0.0`!

```
Honeycomb.start_span(name: "slow_operation") do |span|
  span.add_field("interesting_thing", "banana")
end
```
