### ISSUE TITLE
Is there an OpenTelemetry equivalent for Beeline's `Honeycomb.add_field_to_trace` method?

### ISSUE THREAD

**Issue by modulitos** [honeycombio/beeline-ruby#213]
I'm porting our Honeycomb Beeline client to OTel, and I'm wondering what's the most reasonable way to port a call like: `Honeycomb.add_field_to_trace('job_id', 'abc')` to OTel?

For context, I'd like to add a field to a trace so that I can query all of the spans under it more easily. Unfortunately, it doesn't seem possible to add fields to a trace in the OTel Ruby client. While it provides a way to add attributes to an individual span, there's no way to add the attribute to all spans: https://opentelemetry.io/docs/instrumentation/ruby/manual/#add-attributes-to-a-span

**Comment by MikeGoldsmith** [comment]
Hi @modulitos 

Unfortunately this is something that doesn't translate perfectly between the Beeline and OpenTelemetry. We have made an effort to try to provide similar behaviour in the distros we've built to far (java, .NET, go & node) using a span processor in conjunction with the trace propagation context to add attributes to newly created spans. However, the limitation here is that attributes are only added when new spans are created so it cannot add attributes to existing spans (eg parent spans). In addition, you need to be aware of what attributes you're adding to your propagation context, as these are serialized and sent when communicating to another service (even ones outside of your network).

We haven't got to building a distro for Ruby (yet), but you could use the ones we've created in the other languages as a guide.

- [Java](https://github.com/honeycombio/honeycomb-opentelemetry-java/blob/main/common/src/main/java/io/honeycomb/opentelemetry/sdk/trace/spanprocessors/BaggageSpanProcessor.java)
- [.NET](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/blob/main/src/Honeycomb.OpenTelemetry/BaggageSpanProcessor.cs)
- [go](https://github.com/honeycombio/honeycomb-opentelemetry-go/blob/main/baggage_span_processor.go)
- [Node](https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/main/src/baggage-span-processor.ts)

**Comment by JamieDanielson** [comment]
Also, we recently added an example of this in our example greeting service in the [ruby frontend service](https://github.com/honeycombio/example-greeting-service/tree/main/ruby/frontend). Maybe this will help get closer to what you are trying to do?

**Comment by modulitos** [comment]
I'm stepping back to re-think the purpose of this `Honeycomb.add_field_to_trace` method - is there any documentation on the use cases for adding a field to all spans (or directly to the trace, in Beeline's case)?

I'm not seeing any guidance about when this `add_field_to_trace` method is useful. I found it in the source here: https://github.com/honeycombio/beeline-ruby/blob/4ed0880a82cc85a887bf37f661ca0254702a5af4/lib/honeycomb/client.rb#L81-L85
I wonder if it's easier to refactor these calls to use OTel's `span.set_attribute` method instead :thinking: 

In OTel, I believe I can query for an attribute to find the traces/spans that match. Given that, what's the benefit of adding the attribute to all spans in the trace, instead of just one?

**Comment by MikeGoldsmith** [comment]
Adding an attribute to every span in a trace is useful in some circumstances, primarily when looking at spans in isolation or when using older Honeycomb classic environments. Now, with better querying abilities in Honeycomb and newer environment & service based datasets, the need isn't as strong.

You could totally replace a add to trace with set attribute on the current span and search for a trace that contains a soan with it in the Honeycomb Query Builder.

**Comment by MikeGoldsmith** [comment]
PS I'm gonna close this issue now, as it's not something we are going action but is a good topic for other discover if they have the same question.

Thanks @modulitos 👍🏻

**Comment by modulitos** [comment]
Makes sense - I think I'll replace my `Honeycomb.add_field_to_trace` with `span.set_attribute` then :+1: 

Thanks for the feedback!
