### ISSUE TITLE
Adding fields and empty fields

### ISSUE THREAD

**Issue by carolinelilyyu** [honeycombio/beeline-ruby#215]
Hi Team! I was wondering if there were any **docs on adding columns through specifically Honeycomb Beeline (not Honeytail, etc). I want to add the following default fields, e.g. the request's timestamp. (columns wanted are in the code snippet below)**

Also I was wondering: how come some of the default fields show up but they're empty?

<img width="448" alt="Screen Shot 2022-11-29 at 9 01 50 AM" src="https://user-images.githubusercontent.com/11544724/204549227-d16699ec-91b2-4c38-93c3-1aa6c1860bcd.png">

Some fields I want added/ see but they're empty.
```
Standard:    
    Timestamp
    body_bytes_sent
    bytes_sent
    http_referer
    http_user_agent
    http_x_forwarded_for
    http_x_forwarded_proto
    remote_addr
    remote_user
    request
    request_length
    request_method
    request_path
    request_pathshape
    request_protocol_version
    request_query
    request_query_type
    request_queryshape
    request_shape
    request_time
    request_uri
    server_addr
    status
```

The API docs doesn't have info on adding the default / standard columns. Do you know if there any Honeycomb documentation to customize which default fields to show?  I know how to add custom fields.
I know there's
```
Honeycomb.add_field('postback', request.original_url)
```
i believe this issue should be the autoinstrumentation for ruby beeline. But the code here: https://github.com/honeycombio/libhoney-rb/blob/5a10ab5e206b4d40ad9c9cafb25986edf369f6e5/lib/libhoney/event.rb
seems like it's assuming that the fields get added automatically. I queried in Honeycomb a postback and it has the timestamp, but body_bytes_sent is empty. I also see there's a postback field, but the some of the fields I specified above aren't there.

**Comment by robbkidd** [comment]
@carolinelilyyu and I worked through this question together elsewhere than on this GitHub issue.

### On the Beeline supporting default or standard columns on events:

The desire here was to provide the Beeline a list of field names to treat as an **allowlist**; apply no other fields to events emitted from a Beeline-instrumented application. There is no portion of the Beeline library's API that _directly_ maps to declaring an allowlist for field names. Removing unwanted fields from events can still be done, though with the Ruby Beeline's [presend_hook](https://docs.honeycomb.io/getting-data-in/beeline/ruby/#augmenting-or-scrubbing-spans). In the presend_hook, the collection of fields on an event can be modified in just about anyway you like prior to sending the event on to Honeycomb.

**Honeycomb does not recommend allowlist'ing fields**:

1. The allowlist filter might remove fields necessary for the backend to tie together coherent traces.
2. Fields are free! (†Up to 10,000 distinct column names in a dataset. See below!)
3. You'll miss out on dimensions of behavior state about what is occurring within your instrumented service. Making these dimensions visible is the prime purpose of tracing.

So, I don't recommend filtering fields through an allowlist, but _you can still do it_ if you believe it is the right solution for your situation. Configure a custom presend_hook that deletes entries from `fields` when the field name is not included in a list you define. An [example presend_hook](https://github.com/honeycombio/beeline-ruby/blob/v2.11.0/lib/generators/honeycomb/honeycomb_generator.rb#L26-L38) that [performs some field deletion](https://github.com/honeycombio/beeline-ruby/blob/v2.11.0/lib/generators/honeycomb/honeycomb_generator.rb#L35-L36) appears in the default Honeycomb initializer (provided by [the rails generator during Beeline installation](https://docs.honeycomb.io/getting-data-in/beeline/ruby/#quick-installation)).

### On why an event field allowlist seems appealing and an alternative solution:

The Honeycomb dataset receiving Beeline traces was approaching 10,000 columns. The thought was to curb the column growth by setting an allowlist for field names in the Beeline.

The most frequent reason a dataset grows to 10K distinct column names is from something emitting events with field names that include some high-cardinality data _in the field name_. The general advice when adding fields to events (or parsing events from logs with other instrumentation) is to use static strings for field names (example: `"request_id"`) and not to compute field names from data (example: `"request_${id}"`).
