### ISSUE TITLE
start_span delegates to nil if `configure` hasn't run

### ISSUE THREAD

**Issue by DanielHeath** [honeycombio/beeline-ruby#25]
### Description
Upgraded to 1.0, ran my tests.

### Issue
Loads of test failures - `undefined method `start_span' for nil:NilClass`

Looks like @client is nil in my test environment, since I don't want to send anything.

Maybe `start_span` should be a silent no-op if no client is configured?

**Comment by Sergio-Mira** [comment]
Seeing the same issue on my test environment

**Comment by martin308** [comment]
Hopefully this is fixed with #27, it's being released in `v1.0.1` of the beeline. Feel free to reopen this issue if you're still seeing this after upgrading!
