### ISSUE TITLE
Rails version support is not specified

### ISSUE THREAD

**Issue by sethjohnson-flexe** [honeycombio/beeline-ruby#30]
Hello.  The README does not specify which versions of rails are supported.  The instructions https://docs.honeycomb.io/getting-data-in/ruby/beeline/ specifically reference rails, so this seems relevant.  I am currently unable to install on Rails 4; errors out with ` No such middleware to insert before: Rails::Rack::Logger (RuntimeError)`

**Comment by martin308** [comment]
@sethjohnson-flexe you're correct we should update that! We currently test with this set of rails versions https://github.com/honeycombio/beeline-ruby/blob/master/.travis.yml#L14 down to rails 4.1. I'll see if I can take a quick look into supporting rails 4.0. Which version of ruby are you running with rails 4?

**Comment by sethjohnson-flexe** [comment]
Rails 4.2.11.  Should I open a separate issue about the setup problem then?

**Comment by martin308** [comment]
Yeh that sounds great re opening another issue! I have ideas about this that I can dump into it when you create it 😄

**Comment by sethjohnson-flexe** [comment]
Done https://github.com/honeycombio/beeline-ruby/issues/32
