### ISSUE TITLE
No instrumentation from AWS integration when body consists of binary data

### ISSUE THREAD

**Issue by til** [honeycombio/beeline-ruby#41]
When saving binary data, e.g. the result of zlib compressing a string, to an S3 object using aws-sdk-s3, there seems to be no corresponding instrumentation data received by Honeycomb for the related aws API calls.

When configuring Honeycomb locally with `config.client = Libhoney::LogClient.new(verbose: true)`, it outputs this error:

```
irb(main):002:0> bucket = Aws::S3::Resource.new(client: Aws::S3::Client.new(region: 'eu-central-1')).bucket('[redacted]')
irb(main):004:0> bucket.object('test.txt').put(body: Zlib.deflate('test'))
Honeycomb dataset '' | 2019-11-07T15:14:47+00:00 | Traceback (most recent call last):
        4: from (irb):4
        3: from libhoney (1.14.0) lib/libhoney/event.rb:126:in `send_presampled'
        2: from libhoney (1.14.0) lib/libhoney/client.rb:235:in `send_event'
        1: from libhoney (1.14.0) lib/libhoney/log_transmission.rb:25:in `add'
Encoding::UndefinedConversionError ("\x9C" from ASCII-8BIT to UTF-8)
```

A `pp` on the event data reveals this:

```
   "aws.params"=>
    {:body=>"x\x9C+I-.\x01\x00\x04]\x01\xC1",
     :bucket=>"[redacted]",
     :key=>"test.txt"},
```

So it looks like this is caused by calling `to_json` on `aws.params` which contains a string with a binary encoding.

I locally tried to remove the `:body` key from the `aws.params` hash before sending it, and the error went away.

If it helps – I wouldn't mind having the body data removed from instrumentation, especially as it can become quite large in the case of putting data on S3.

**Comment by martin308** [comment]
@til thanks for the report! I'm taking a look now

**Comment by til** [comment]
After upgrading libhoney to 1.14.1 which includes https://github.com/honeycombio/libhoney-rb/pull/37, we could see spans for `aws` calls being recorded on Honeycomb, so the most important part of this issue can be considered fixed now. (Side note: after confirming it works as intended, we ended up disabling the aws integration because we're uploading relatively large objects to s3, and were not sure if sending the same data again to Honeycomb would incur significant overhead).

When running it with `Libhoney::LogClient`, the error as initially reported still occurs. Do you plan to apply the same cleaning to the `Libhoney::LogClient` as well?

**Comment by martin308** [comment]
@til yup we can make that same fix to the `Libhoney::LogClient` as well. Did you try using the [scrubbing functionality](https://docs.honeycomb.io/getting-data-in/ruby/beeline/#augmenting-or-scrubbing-spans) to remove the upload data before sending the events to honeycomb? My thoughts was that that would get us the best possible result. If people want the data then they can have it but it can be removed if needed.

**Comment by til** [comment]
Thanks for the hint – I've discovered the scrubbing functionality after submitting this issue, and didn't get around to use it yet but it does indeed look exactly like what we need for preventing problems with the upload data.
