### ISSUE TITLE
v1 span changes

### ISSUE THREAD

**Issue by grncdr** [honeycombio/beeline-ruby#47]
Not sure if this is the right place to bring this up, but I've been upgrading from v0.8 and noticed a couple of usability issues:

1. span names are no longer very descriptive. E.g. spans are now named `sql.active_record` instead of `MyModel Load`.
2. Normal requests always have 2 spans: `http_request` and `process_action.action_controller`. Previously I could count on fields added inside controller methods belonging to the outermost span of a trace. It was common for me to write queries like `trace.parent_id does-not-exist AND app.my_custom_field = foo` to find certain requests but this no longer works.

Any suggestions for how to work around this and/or get some of the old behavior back?

**Comment by martin308** [comment]
Unfortunately for number one that was a consequence of supporting active notifications and having to handle the events more generically.

For the second point you could add trace fields using `add_field_to_trace` there is some more information on this over here https://docs.honeycomb.io/getting-data-in/ruby/beeline/#adding-context-to-events

**Comment by martin308** [comment]
Actually for the first one, you can add a handler for the active support events and add whatever data in whatever form you would like by interrogating the events. Here is a test that shows how it works https://github.com/honeycombio/beeline-ruby/blob/master/spec/honeycomb/integrations/active_support_spec.rb#L45

**Comment by DanielHeath** [comment]
You could filter for span name `process_action.action_controller` instead of `parent_id does-not-exist`.

**Comment by directionless** [comment]
I've just started using this, and I've also been frustrated by the span names. Right now, I'm monkeypatching to fix a narrow use case, but looking at the [rails events](https://guides.rubyonrails.org/active_support_instrumentation.html) I see that they're all very different.

I think a reasonable approach is to build a mapping of notification to formatting. (And perhaps also additional fields?)

I'm not sure what the preferred way to go about this would be. 
1. a giant case statement in the `start` method seems clearly wrong
2. a map of `name => Proc` could work, but feels unweidly
3. a bunch of modules, which can be instantiated using something like `Object.const_get(name)`

I'm sorta partial to (3) here. I'm happy to take a first pass at that, but I don't know if it would be welcome
