### ISSUE TITLE
Too much data in the redis integration

### ISSUE THREAD

**Issue by directionless** [honeycombio/beeline-ruby#55]
By default, the redis integration includes _all_ of the data in a SET command. This feels unreasonable to me. This feels like it should be exposed in the configuration via something simpler than `presend_hook`. 

I'm not sure what it would look like

**Comment by directionless** [comment]
I monkeyed patched this to have a fairly rich sanitizer. Though, I suspect a simpler path would be to either not include any of the command, or to include only the first 2 fields (generally the command and keyname). Not perfect, but maybe good enough.

Could also provide some sort of config hook.

**Comment by martin308** [comment]
I think we are going to err on the side of collecting more information and then allowing people to remove the data that they don't want to send either by disabling the integration or by using the presend_hook to remove any keys that they don't want once they have experienced the full load of information.

I'm curious what you would need to monkey patch in the library to have a fairly rich sanitiser? The presend_hook gives you the entire event to sanitise as you wish so I wouldn't have thought you would need to do any monkey patching to sanitise the events.

**Comment by directionless** [comment]
I disagree quite strongly, for several reasons.

I recognize there are various knobs for redacting and sanitizing data, but I believe one should have safe defaults. And I believe the current approach is harmful.

---

Foremost is something around privacy and security, and expectations therein. 

While I am not a rails expert, my understanding of the rails  ecosystem is that a _lot_ of data hangs out in redis.

A simple example is the rails html fragment caching. Rails caches html in a [variety of ways](https://guides.rubyonrails.org/caching_with_rails.html). This is commonly in redis. And since it's the html cache, this includes a lot of sensitive information. 

The handful of rails developers I talked to were flabbergasted that all their html would get sent to honeycomb, and immediately pointed out that it would likely require some customer notifications under the GDPR.

As an analogy -- Would it be reasonable for the beeline gem to install an integration that pushes sql dumps for all databases to honeycomb? There are absolutely times that would be valuable. But I think it would be an unreasonable default.

---

I have a secondary concern about performance, and data retention. In the common case, redis commands and key names are small and high value. But key data is larger and lower value. You can see this reflected in how many tools analyze redis cache utilization.

Defaulting to transmitting it all is going to chew network bandwidth and quota for low value data. 

---

I think this is, ultimately, a philosophy discussion.
* What use cases are common, and how can things be frictionless for them?
* How useful should the beeline gem be out of the box? (vs needing custom configuration)
* What ends up needing less configuration anyhow.

**Comment by directionless** [comment]
> I'm curious what you would need to monkey patch in the library to have a fairly rich sanitiser? The presend_hook gives you the entire event to sanitise as you wish so I wouldn't have thought you would need to do any monkey patching to sanitise the events.

I found it much simpler to monkey patch the thing generating the data, to simply not generate it. Then to think about how to fix it after the fact. I suspect this is faster, and also less error prone.

**Comment by directionless** [comment]
I recognize we may have some fundamental disagree about what a reasonable default is, but here are things I think would be more okay:

* default to only keeping the command and keyname for redis
* don't include all integrations by default, instead require explicit opt-in
* improve documentation to indicate exactly what is being collected, and why an end user might care
