### ISSUE TITLE
Allow middleware insertion point to be configurable

### ISSUE THREAD

**Issue by rossatclutter** [honeycombio/beeline-ruby#56]
I tried following the [Quick Installation instructions for Ruby](https://docs.honeycomb.io/getting-data-in/ruby/beeline/#quick-installation) on an existing Rails app and our Rake task that runs the asset pipeline crashes with the following exception:

```
No such middleware to insert before: Rails::Rack::Logger
```

I've omitted the exact stack trace because it's misleading — it points deep into Railties innards — but I uncovered the root cause here:

https://github.com/honeycombio/beeline-ruby/blob/7fe276c3d027627e1f3659fb40ad098e8df56154/lib/honeycomb/integrations/railtie.rb#L12-L17

Our application uses a custom logger, which interferes with the integration point which assumes the logger will always be `Rails::Rack::Logger`. Here's a simplified version of the code the application uses to demonstrate:

```ruby
  config.middleware.swap Rails::Rack::Logger, Silencer::Logger, # ...
```

Would you be able to add a hook to configure the middleware insertion point? I'm also open to other ways of solving this problem, but I'm not an expert on Rails configuration.

**Comment by martin308** [comment]
@rossatclutter you can disable the railtie and insert the middleware where you would like it using [these instructions](https://docs.honeycomb.io/getting-data-in/ruby/beeline/#customizing-middleware-location-in-a-rails-application). Let me know if this doesn't solve your issue!

**Comment by rossatclutter** [comment]
Thanks, I'll give that a try!

It would be nice if the integrations list could be configured in code rather than the environment variable, since a failure to set that environment variable would mean a crashing production server with a hard-to-diagnose error.

**Comment by rossatclutter** [comment]
Confirming: that fixed my issue. Thanks!

**Comment by martin308** [comment]
@rossatclutter hooray! Agreed, it would be nicer to have it configured in code. I tried to have it work that way but it makes the code much more complicated as it loads each integration by requiring each file and some of the things those files do, need to happen early or at certain points of the apps startup so if they don't happen things are even more confusing

**Comment by rossatclutter** [comment]
Did a bit more digging and experimentation: any reason not to cut a new version of the gem that includes #49? I kludged it into our configuration with the honeycomb-beeline gem and it worked fine.

**Comment by martin308** [comment]
@rossatclutter there is not, there was some talk at the time about rolling some other fixes into major a release but I think the holidays disrupted that. I'm in two minds if this deserves a major version bump or not as it could potentially break someones app who doesn't have `ActionDispatch::ShowExceptions` middleware in their stack 😬
