### ISSUE TITLE
Custom context in tracing spans

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-ruby#8]
The other Beelines let you span and then add fields on the spans (or whole trace), like so:

```golang
span, ctx := beeline.StartSpan(ctx, "first_span")

beeline.AddField(ctx, "user_id", userID)

span.Send()
```

Would be pretty nice to get this functionality in Ruby beeline as well.

**Comment by rhymes** [comment]
@nathanleclaire how did you work this out? using libhoney manually?

**Comment by martin308** [comment]
This has been completed in `v1.0.0`!

```
Honeycomb.start_span(name: "first_span") do |span|
  span.add_field("user_id", user_id)
end
```
