### ISSUE TITLE
Unpacking actioncontroller params to separate keys

### ISSUE THREAD

**Issue by DanielHeath** [honeycombio/beeline-ruby#80]
I've just upgraded to 2.0 (nice work!).

I'm trying to understand the tradeoffs between different encodings of `process_action.action_controller.params`.

 * Currently it's encoded as a hash like `{"foo" => "bar"}` (large, hard to query on).
 * Converting the hash to JSON like `{"foo": "bar"}` (still large, but much easier to query on if honeycomb added JSON operators to the function set). If you have `action_controller` you have a fast JSON encoder for hashes.
 * Sending it as `process_action.action_controller.params.foo = bar` (smallest, easiest to query on, but generates lots of distinct field names).

**Comment by lizthegrey** [comment]
the third one is best for us as it lets us encode each column separately using a table lookup rather than needing to compress the entire string.

so it saves you storage and query time!

**Comment by DanielHeath** [comment]
Should that be the default then? PR accepted?

**Comment by DanielHeath** [comment]
https://github.com/DanielHeath/beeline-ruby/commit/0bbd491311229239ceb39c59e2e6f8d622eab25e

**Comment by DanielHeath** [comment]
I assign copyright for the above diff to honeycomb.

**Comment by lizthegrey** [comment]
This is done already by JSON unpack in Honeycomb. See dataset settings.

**Comment by DanielHeath** [comment]
The previous code isn't sending valid JSON to Honeycomb; it's sending the ruby serialization of a hash.

**Comment by lizthegrey** [comment]
Libhoney does unpack hashes to JSON, I'm pretty sure. See https://github.com/honeycombio/libhoney-rb/blob/master/lib/libhoney/transmission.rb#L190

**Comment by DanielHeath** [comment]
Ahh - I was previously seeing the ruby format, but that was on a much older version.


Thanks,
Daniel Heath

**Comment by lizthegrey** [comment]
Yup, the encoding as JSON is new as of v2.0

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
