### ISSUE TITLE
Initializer Breaks When HONEYCOMB_DISABLE_AUTOCONFIGURE is set to true

### ISSUE THREAD

**Issue by mstruve** [honeycombio/beeline-ruby#81]
When configuring Honeycomb, if HONEYCOMB_DISABLE_AUTOCONFIGURE is set to true then the configuration setup breaks with the following error. 
```
NoMethodError: undefined method `notification_events=' for #<Honeycomb::Configuration:0x...>
 [PROJECT_ROOT]/config/initializers/honeycomb.rb:12 :in `block in <main>`
10     config.write_key = honeycomb_api_key
11     config.dataset = "rails"
12     config.notification_events = %w[
13       sql.active_record
14       render_template.action_view
```

Further details and backtrace: https://app.honeybadger.io/fault/66984/57351c7f120516fea1b2242d06652256

**Comment by lizthegrey** [comment]
workaround: set HONEYCOMB_INTEGRATIONS=active_support to avoid this error.

**Comment by ajvondrak** [comment]
If you "disable autoconfigure", it just refrains from `require`-ing the integration patches. The `notification_events` attribute is defined by https://github.com/honeycombio/beeline-ruby/blob/865358e2f59255112c56575c8d17d93343881b2f/lib/honeycomb/integrations/active_support.rb#L11 which gets mixed in by https://github.com/honeycombio/beeline-ruby/blob/865358e2f59255112c56575c8d17d93343881b2f/lib/honeycomb/integrations/active_support.rb#L82 

So you can put `require 'honeycomb/integrations/active_support'` at the top of the initializer (or, as @lizthegrey says, use the env var). But it's a good point: it's unexpected for the `Honeycomb.configure` block to explode if you disable all the default integrations. Makes it so you can't actually reliably toggle it on/off with the same configuration. To _actually_ turn off all integrations without causing an exception, you'd have to comment out the `notification_events`.

Good issue! 😅

**Comment by dzajic** [comment]
Yeah, this is pretty insidious. Trying to disable something when there's a problem actually makes a much worse problem. One of the nice things about controlling things through ENVs is that it doesn't require a whole PR/CI/deploy cycle, which takes minutes. This took down our whole Rails app, luckily it was only staging.

**Comment by vreynolds** [comment]
Hello,

We are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.

**Comment by mstruve** [comment]
Really appreciate the communication on this and +1 for trimming that backlog!
