### ISSUE TITLE
Support for sampler hook

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-ruby#9]
In the Python Beeline you can add a "sampler hook" which is a little function allowing you to have custom sampling logic based on the properties of the event. For instance, you could refuse to sample all health checks to cut down on volume. This would be a nice addition to the Ruby Beeline.

**Comment by martin308** [comment]
This has been completed in `v1.0.0`!

```
class CustomSampler
  extend Honeycomb::DeterministicSampler

  def self.sample(fields)
    case fields["app.response_code"]
    when 0
      [false, 0]
    when 200
      rate = 100
      [should_sample(rate, fields["trace.trace_id"]), rate]
    else
      [true, 1]
    end
  end
end

Honeycomb.configure do |config|
  config.sample_hook do |fields|
    CustomSampler.sampler(fields)
  end
end
```
